In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import xgboost as xgb
import gseapy as gp
from scipy import stats
from scipy.stats import ttest_ind
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [10]:
# Reading the file into a dataframe
file = "43587_2024_572_MOESM11_ESM.xlsx"

sheet = pd.read_excel(file, sheet_name='Extended Data Fig 1m')
sheet

,Metabolome data of 98 large intestinal tissues (related to Extended Data Fig. 1m).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Metabolites,2-7-A,2-7-T,2-7-D,2-7-R,2-8-A,2-8-T,2-8-D,2-8-R,2-9-A,...,3-13-D,3-13-R,3-19-D,3-19-T,3-19-A,3-19-R,3-18-A,3-18-T,3-18-D,3-18-R
2,(RS)-Mevalonic acid,10116238.17,1967645.195,1730029.709,2548579.522,1124059.931,1044249.308,998527.1616,1017072.109,1684355.874,...,1553776.897,1847166.353,1055002.221,1252681.891,1039339.244,2378215.014,1094206.179,2716221.239,1416556.865,1109912.976
3,(S)-1-Pyrroline-5-carboxylate/1-Pyrroline-2-ca...,6616219.104,24224061.07,16195572.42,6799085.138,12646999.15,28218375.34,25741012.2,19565289.51,29396267.27,...,21350819.31,23566501.37,19175883.62,14422192.92,15094670.29,26339850.76,21524625.75,18168012.36,22859166.02,23884801.23
4,"1-(beta-D-Ribofuranosyl)-1,4-dihydronicotinamide",654985.8926,714316.518,950139.8268,2083274.716,1040267,1222648.884,3005875.658,2541187.469,2789769.518,...,614403.548,1794772.428,643146.2461,1094489.229,563606.2461,904860.6551,803764.8787,650886.3017,691335.177,676119.1596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,Val-Val,2172617.553,201270.868,363273.6669,499395.4204,370991.7981,149262.2722,82292.80811,110433.3642,89825.12421,...,647513.722,342373.4467,516643.6841,236193.8586,285974.5654,404264.5036,333578.6312,384276.4544,301806.9965,496028.7799
613,Xanthosine,394.988149,21755.33581,394.988149,394.988149,24787.97267,10929.46399,394.988149,27363.26474,2026199.173,...,28671.31846,221476.9306,25245.86123,64933.05314,15601182.99,1455901.042,38819.06427,1611063.574,1089360.499,394.988149
614,Xanthosine 5'-monophosphate,394.988149,347956.3909,424850.2878,260485.9529,1028449.973,545757.2977,776788.2218,231957.4014,638656.6755,...,1028437.966,461794.4761,403932.9914,707532.4268,751755.4442,393304.3227,645771.2593,425150.912,476948.3249,637789.9562
615,xanthurenic acid,162354.8792,114167.8965,125981.6241,128689.93,111024.8443,145946.9945,111651.2735,120060.4648,141306.9106,...,152549.5932,108776.5007,108955.402,78619.25117,127830.2699,141989.9707,90696.17297,148967.6835,104433.8636,58339.94101
616,Indoleacetic acid,2069467.592,339662.6511,506299.2228,1088469.331,219121.283,226935.3969,178009.0693,194992.7737,292039.4371,...,891753.7123,614674.6042,926768.4517,481995.4331,575768.0994,759377.7968,279278.122,1163905.672,450871.3597,118809.2152

In [11]:
sheet.iloc[1,0]

'Metabolites'

In [14]:
# This cleans the transcript table, setting the first column
# to be the index and then removing the first two blank rows

cleaned_data = sheet.copy()

if sheet.iloc[1,0] == 'Metabolites':
   
    sheet.columns = sheet.iloc[1]
    sheet = sheet.set_index("Metabolites")
    sheet = sheet[2:]

    # Make sure the table is all numbers and not strings
    sheet = sheet.apply(pd.to_numeric, errors='coerce')
    sheet = sheet[sheet.index.notna()]
    cleaned_data = sheet
else:
    print("Metabolomics Table Already Clean")

cleaned_data.head()

Metabolomics Table Already Clean

1,2-7-A,2-7-T,2-7-D,2-7-R,2-8-A,2-8-T,2-8-D,2-8-R,2-9-A,2-9-T,...,3-13-D,3-13-R,3-19-D,3-19-T,3-19-A,3-19-R,3-18-A,3-18-T,3-18-D,3-18-R
Metabolites,,,,,,,,,,,,,,,,,,,,,
(RS)-Mevalonic acid,1.011624e+07,1.967645e+06,1.730030e+06,2548579.522,1.124060e+06,1.044249e+06,9.985272e+05,1.017072e+06,1.684356e+06,2.165682e+06,...,1.553777e+06,1.847166e+06,1.055002e+06,1.252682e+06,1.039339e+06,2.378215e+06,1.094206e+06,2.716221e+06,1.416557e+06,1.109913e+06
(S)-1-Pyrroline-5-carboxylate/1-Pyrroline-2-carboxylic acid,6.616219e+06,2.422406e+07,1.619557e+07,6799085.138,1.264700e+07,2.821838e+07,2.574101e+07,1.956529e+07,2.939627e+07,1.462043e+07,...,2.135082e+07,2.356650e+07,1.917588e+07,1.442219e+07,1.509467e+07,2.633985e+07,2.152463e+07,1.816801e+07,2.285917e+07,2.388480e+07
"1-(beta-D-Ribofuranosyl)-1,4-dihydronicotinamide",6.549859e+05,7.143165e+05,9.501398e+05,2083274.716,1.040267e+06,1.222649e+06,3.005876e+06,2.541187e+06,2.789770e+06,2.152745e+06,...,6.144035e+05,1.794772e+06,6.431462e+05,1.094489e+06,5.636062e+05,9.048607e+05,8.037649e+05,6.508863e+05,6.913352e+05,6.761192e+05
1-(sn-Glycero-3-phospho)-1D-myo-inositol,1.911745e+06,2.396950e+06,2.953359e+06,2976480.140,5.967506e+06,2.602516e+06,2.453928e+06,1.081012e+06,3.018984e+06,5.173003e+06,...,4.636016e+06,2.106010e+06,2.437681e+06,2.265626e+06,1.818942e+06,1.734650e+06,2.478232e+06,2.475604e+06,1.531101e+06,2.257566e+06
12-Hydroxy-12-octadecanoylcarnitine,5.378064e+05,1.085144e+06,9.000020e+05,1463497.476,4.830553e+06,3.292883e+06,2.236182e+06,5.157463e+06,2.505046e+06,3.329483e+06,...,1.670183e+06,1.537764e+06,1.519936e+06,3.066999e+06,1.477562e+06,1.236482e+06,1.948629e+06,1.598310e+06,1.053866e+06,2.535359e+06

In [15]:

nan_counts = cleaned_data.isna().sum().sum()

nan_counts

np.int64(0)

In [16]:
log = np.log2(cleaned_data + 1.0)
    
scaler = StandardScaler()
norm = pd.DataFrame( scaler.fit_transform(log),index=log.index, columns=log.columns)
    
preprocessed_scaled = norm
preprocessed_scaled.head()

1,2-7-A,2-7-T,2-7-D,2-7-R,2-8-A,2-8-T,2-8-D,2-8-R,2-9-A,2-9-T,...,3-13-D,3-13-R,3-19-D,3-19-T,3-19-A,3-19-R,3-18-A,3-18-T,3-18-D,3-18-R
Metabolites,,,,,,,,,,,,,,,,,,,,,
(RS)-Mevalonic acid,0.129057,-0.452853,-0.581732,-0.414906,-0.731564,-0.646648,-0.672846,-0.641199,-0.544496,-0.461449,...,-0.636013,-0.503293,-0.743065,-0.636734,-0.632007,-0.437143,-0.711232,-0.407009,-0.568314,-0.636120
(S)-1-Pyrroline-5-carboxylate/1-Pyrroline-2-carboxylic acid,-0.031701,0.532149,0.325913,-0.023603,0.251997,0.559191,0.545390,0.462644,0.584117,0.300442,...,0.398491,0.505838,0.410113,0.321103,0.377592,0.534299,0.459826,0.362886,0.490779,0.549250
"1-(beta-D-Ribofuranosyl)-1,4-dihydronicotinamide",-0.907259,-0.850409,-0.824931,-0.495297,-0.763044,-0.588957,-0.259699,-0.299348,-0.345345,-0.463839,...,-1.002294,-0.514698,-0.939864,-0.689653,-0.862917,-0.827510,-0.832489,-0.985785,-0.841495,-0.827568
1-(sn-Glycero-3-phospho)-1D-myo-inositol,-0.501726,-0.375419,-0.364701,-0.353013,-0.053210,-0.312630,-0.335756,-0.618438,-0.314179,-0.114066,...,-0.204443,-0.451317,-0.410046,-0.404450,-0.420836,-0.564614,-0.389881,-0.444586,-0.538703,-0.361884
12-Hydroxy-12-octadecanoylcarnitine,-0.981885,-0.686351,-0.846931,-0.636111,-0.139099,-0.226569,-0.370591,-0.035108,-0.387834,-0.289863,...,-0.607492,-0.575950,-0.597880,-0.285735,-0.499265,-0.701372,-0.484386,-0.621840,-0.680946,-0.317061

In [17]:
#If needed make the graphs of before and after data such as in the workflow, but for now just moving on to make the PCAs

In [ ]:
import re

pattern = r'^(?P<Cohort>\d+)-(?P<Sbuject>\d+)-(?P<Colon Segment>[ATDR])$'

segment_map = {'A': 'Ascending colon','T': 'Transverse colon','D': 'Descending colon','R': 'Rectum'}

rows = []


for col in map(str, cleaned_data.columns):
    match = re.match(pattern, col)
    if match:
        sample_dict = match.groupdict()
        sample_dict['group'] = int(sample_dict['group'])
        sample_dict['age'] = int(sample_dict['age'])
        sample_dict['test'] = sample_dict['test']
        sample_dict['Sample'] = col
        rows.append(sample_dict)
    
sample_df = pd.DataFrame(rows)
if len(sample_df) == 0:
    print(f"Warning: No parsable sample names found in metabolomics column")

meta_data_sheet = '43587_2024_572_MOESM4_ESM.xlsx'
    
# Remove duplicate samples (keeping track of which we've seen)
before = len(sample_df)
sample_df = sample_df.drop_duplicates(subset=['Sample'])
after = len(sample_df)
if before > after:
    print(f"Removed {before - after} duplicate samples")
    

sample_info = sample_df
    
# Count unique combinations by grouping variables
group_counts = (
    sample_df
    .groupby(['group', 'age', 'test'])
    .size()
    .reset_index(name = 'Count')
    .sort_values('Count', ascending=False)
)
    


# Show summary of all groups across sheets
print("\nAll experimental groups:")
all_groups_summary = group_counts.assign(Sheet='Extended Data Fig 1m')
display(all_groups_summary)

All experimental groups:

    group  age test  Count                 Sheet
0       2    2    A      1  Extended Data Fig 1m
1       2    2    D      1  Extended Data Fig 1m
2       2    2    R      1  Extended Data Fig 1m
3       2    2    T      1  Extended Data Fig 1m
4       2    3    A      1  Extended Data Fig 1m
..    ...  ...  ...    ...                   ...
89      3   19    R      1  Extended Data Fig 1m
90      3   19    T      1  Extended Data Fig 1m
91      3   28    A      1  Extended Data Fig 1m
92      3   28    D      1  Extended Data Fig 1m
93      3   28    T      1  Extended Data Fig 1m

[94 rows x 5 columns]

In [78]:
from umap.umap_ import UMAP
import seaborn as sns

X = metabolimics.T

# Perform PCA
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X)

# Perform UMAP
umap_model = UMAP(n_components=2, random_state=42, n_neighbors=15, min_dist=0.1)
X_umap = umap_model.fit_transform(X)

meta = sample_info.set_index('Sample').loc[X.index].reset_index()

# Create DataFrames for plotting
pca_df = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
pca_df = pd.concat([pca_df, meta], axis=1)

umap_df = pd.DataFrame(X_umap, columns=['UMAP1', 'UMAP2'])
umap_df = pd.concat([umap_df, meta], axis=1)

# Plot PCA and UMAP
fig, axes = plt.subplots(2, 2, figsize=(20, 16))

# PCA by Condition
sns.scatterplot(data=pca_df, x='PC1', y='PC2', hue='Condition', 
                style='Genotype', s=150, alpha=0.7, ax=axes[0, 0])
axes[0, 0].set_title(f'PCA by Condition\n(PC1: {pca.explained_variance_ratio_[0]:.2%}, PC2: {pca.explained_variance_ratio_[1]:.2%})', 
                     fontsize=16, weight='bold')
axes[0, 0].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

# PCA by Genotype
sns.scatterplot(data=pca_df, x='PC1', y='PC2', hue='Genotype', 
                style='Condition', s=150, alpha=0.7, ax=axes[0, 1])
axes[0, 1].set_title(f'PCA by Genotype\n(PC1: {pca.explained_variance_ratio_[0]:.2%}, PC2: {pca.explained_variance_ratio_[1]:.2%})', 
                     fontsize=16, weight='bold')
axes[0, 1].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

# UMAP by Condition
sns.scatterplot(data=umap_df, x='UMAP1', y='UMAP2', hue='Condition', 
                style='Genotype', s=150, alpha=0.7, ax=axes[1, 0])
axes[1, 0].set_title('UMAP by Condition', fontsize=16, weight='bold')
axes[1, 0].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

# UMAP by Genotype
sns.scatterplot(data=umap_df, x='UMAP1', y='UMAP2', hue='Genotype', 
                style='Condition', s=150, alpha=0.7, ax=axes[1, 1])
axes[1, 1].set_title('UMAP by Genotype', fontsize=16, weight='bold')
axes[1, 1].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

# Additional plot by Age
fig, axes = plt.subplots(1, 2, figsize=(20, 8))

sns.scatterplot(data=pca_df, x='PC1', y='PC2', hue='Age', 
                style='Condition', s=150, alpha=0.7, ax=axes[0], palette='viridis')
axes[0].set_title('PCA by Age', fontsize=16, weight='bold')
axes[0].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

sns.scatterplot(data=umap_df, x='UMAP1', y='UMAP2', hue='Age', 
                style='Condition', s=150, alpha=0.7, ax=axes[1], palette='viridis')
axes[1].set_title('UMAP by Age', fontsize=16, weight='bold')
axes[1].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

/usr/local/python/3.12.1/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

KeyError: "['F-A', 'F-T', 'F-D', 'F-R'] not in index"