In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import xgboost as xgb
import gseapy as gp
from scipy import stats
from scipy.stats import ttest_ind
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [12]:
# Reading the file into a dataframe
file = "43587_2024_572_MOESM11_ESM.xlsx"

sheet = pd.read_excel(file, sheet_name='Extended Data Fig 1m')
sheet

,Metabolome data of 98 large intestinal tissues (related to Extended Data Fig. 1m).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Metabolites,2-7-A,2-7-T,2-7-D,2-7-R,2-8-A,2-8-T,2-8-D,2-8-R,2-9-A,...,3-13-D,3-13-R,3-19-D,3-19-T,3-19-A,3-19-R,3-18-A,3-18-T,3-18-D,3-18-R
2,(RS)-Mevalonic acid,10116238.17,1967645.195,1730029.709,2548579.522,1124059.931,1044249.308,998527.1616,1017072.109,1684355.874,...,1553776.897,1847166.353,1055002.221,1252681.891,1039339.244,2378215.014,1094206.179,2716221.239,1416556.865,1109912.976
3,(S)-1-Pyrroline-5-carboxylate/1-Pyrroline-2-ca...,6616219.104,24224061.07,16195572.42,6799085.138,12646999.15,28218375.34,25741012.2,19565289.51,29396267.27,...,21350819.31,23566501.37,19175883.62,14422192.92,15094670.29,26339850.76,21524625.75,18168012.36,22859166.02,23884801.23
4,"1-(beta-D-Ribofuranosyl)-1,4-dihydronicotinamide",654985.8926,714316.518,950139.8268,2083274.716,1040267,1222648.884,3005875.658,2541187.469,2789769.518,...,614403.548,1794772.428,643146.2461,1094489.229,563606.2461,904860.6551,803764.8787,650886.3017,691335.177,676119.1596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,Val-Val,2172617.553,201270.868,363273.6669,499395.4204,370991.7981,149262.2722,82292.80811,110433.3642,89825.12421,...,647513.722,342373.4467,516643.6841,236193.8586,285974.5654,404264.5036,333578.6312,384276.4544,301806.9965,496028.7799
613,Xanthosine,394.988149,21755.33581,394.988149,394.988149,24787.97267,10929.46399,394.988149,27363.26474,2026199.173,...,28671.31846,221476.9306,25245.86123,64933.05314,15601182.99,1455901.042,38819.06427,1611063.574,1089360.499,394.988149
614,Xanthosine 5'-monophosphate,394.988149,347956.3909,424850.2878,260485.9529,1028449.973,545757.2977,776788.2218,231957.4014,638656.6755,...,1028437.966,461794.4761,403932.9914,707532.4268,751755.4442,393304.3227,645771.2593,425150.912,476948.3249,637789.9562
615,xanthurenic acid,162354.8792,114167.8965,125981.6241,128689.93,111024.8443,145946.9945,111651.2735,120060.4648,141306.9106,...,152549.5932,108776.5007,108955.402,78619.25117,127830.2699,141989.9707,90696.17297,148967.6835,104433.8636,58339.94101
616,Indoleacetic acid,2069467.592,339662.6511,506299.2228,1088469.331,219121.283,226935.3969,178009.0693,194992.7737,292039.4371,...,891753.7123,614674.6042,926768.4517,481995.4331,575768.0994,759377.7968,279278.122,1163905.672,450871.3597,118809.2152

In [13]:
sheet.iloc[1,0]

'Metabolites'

In [14]:
# This cleans the transcript table, setting the first column
# to be the index and then removing the first two blank rows

cleaned_data = sheet.copy()

if sheet.iloc[1,0] == 'Metabolites':
   
    sheet.columns = sheet.iloc[1]
    sheet = sheet.set_index("Metabolites")
    sheet = sheet[2:]

    # Make sure the table is all numbers and not strings
    sheet = sheet.apply(pd.to_numeric, errors='coerce')
    sheet = sheet[sheet.index.notna()]
    cleaned_data = sheet
else:
    print("Metabolomics Table Already Clean")

cleaned_data.head()

1,2-7-A,2-7-T,2-7-D,2-7-R,2-8-A,2-8-T,2-8-D,2-8-R,2-9-A,2-9-T,...,3-13-D,3-13-R,3-19-D,3-19-T,3-19-A,3-19-R,3-18-A,3-18-T,3-18-D,3-18-R
Metabolites,,,,,,,,,,,,,,,,,,,,,
(RS)-Mevalonic acid,1.011624e+07,1.967645e+06,1.730030e+06,2548579.522,1.124060e+06,1.044249e+06,9.985272e+05,1.017072e+06,1.684356e+06,2.165682e+06,...,1.553777e+06,1.847166e+06,1.055002e+06,1.252682e+06,1.039339e+06,2.378215e+06,1.094206e+06,2.716221e+06,1.416557e+06,1.109913e+06
(S)-1-Pyrroline-5-carboxylate/1-Pyrroline-2-carboxylic acid,6.616219e+06,2.422406e+07,1.619557e+07,6799085.138,1.264700e+07,2.821838e+07,2.574101e+07,1.956529e+07,2.939627e+07,1.462043e+07,...,2.135082e+07,2.356650e+07,1.917588e+07,1.442219e+07,1.509467e+07,2.633985e+07,2.152463e+07,1.816801e+07,2.285917e+07,2.388480e+07
"1-(beta-D-Ribofuranosyl)-1,4-dihydronicotinamide",6.549859e+05,7.143165e+05,9.501398e+05,2083274.716,1.040267e+06,1.222649e+06,3.005876e+06,2.541187e+06,2.789770e+06,2.152745e+06,...,6.144035e+05,1.794772e+06,6.431462e+05,1.094489e+06,5.636062e+05,9.048607e+05,8.037649e+05,6.508863e+05,6.913352e+05,6.761192e+05
1-(sn-Glycero-3-phospho)-1D-myo-inositol,1.911745e+06,2.396950e+06,2.953359e+06,2976480.140,5.967506e+06,2.602516e+06,2.453928e+06,1.081012e+06,3.018984e+06,5.173003e+06,...,4.636016e+06,2.106010e+06,2.437681e+06,2.265626e+06,1.818942e+06,1.734650e+06,2.478232e+06,2.475604e+06,1.531101e+06,2.257566e+06
12-Hydroxy-12-octadecanoylcarnitine,5.378064e+05,1.085144e+06,9.000020e+05,1463497.476,4.830553e+06,3.292883e+06,2.236182e+06,5.157463e+06,2.505046e+06,3.329483e+06,...,1.670183e+06,1.537764e+06,1.519936e+06,3.066999e+06,1.477562e+06,1.236482e+06,1.948629e+06,1.598310e+06,1.053866e+06,2.535359e+06

In [15]:

nan_counts = cleaned_data.isna().sum().sum()

nan_counts

np.int64(0)

In [16]:
log = np.log2(cleaned_data + 1.0)
    
scaler = StandardScaler()
norm = pd.DataFrame( scaler.fit_transform(log.T).T,index=log.index, columns=log.columns)
    
preprocessed_scaled = norm
preprocessed_scaled.head()

1,2-7-A,2-7-T,2-7-D,2-7-R,2-8-A,2-8-T,2-8-D,2-8-R,2-9-A,2-9-T,...,3-13-D,3-13-R,3-19-D,3-19-T,3-19-A,3-19-R,3-18-A,3-18-T,3-18-D,3-18-R
Metabolites,,,,,,,,,,,,,,,,,,,,,
(RS)-Mevalonic acid,3.277134,0.411151,0.185873,0.863984,-0.568897,-0.697814,-0.776184,-0.743973,0.139039,0.579013,...,-0.002211,0.300551,-0.679881,-0.379256,-0.706063,0.742879,-0.616015,0.975496,-0.164054,-0.591067
(S)-1-Pyrroline-5-carboxylate/1-Pyrroline-2-carboxylic acid,-1.621076,0.628588,-0.069299,-1.573816,-0.498004,0.893154,0.733874,0.258349,0.964041,-0.246659,...,0.409734,0.580884,0.223501,-0.270323,-0.191325,0.773739,0.423788,0.129913,0.528060,0.604140
"1-(beta-D-Ribofuranosyl)-1,4-dihydronicotinamide",-0.544088,-0.425881,-0.036983,1.033248,0.086555,0.306769,1.533036,1.304104,1.431328,1.077965,...,-0.631281,0.830046,-0.568955,0.155819,-0.748919,-0.103546,-0.265050,-0.552647,-0.470460,-0.500799
1-(sn-Glycero-3-phospho)-1D-myo-inositol,-0.477542,0.056820,0.549992,0.568416,2.211773,0.251215,0.112323,-1.824473,0.601915,1.874223,...,1.615292,-0.248898,0.096630,-0.076300,-0.595105,-0.707206,0.135607,0.133100,-1.002095,-0.084719
12-Hydroxy-12-octadecanoylcarnitine,-1.072498,-0.423148,-0.596197,-0.146454,0.958168,0.603694,0.245709,1.018743,0.350736,0.613919,...,-0.024252,-0.100664,-0.111451,0.537957,-0.137606,-0.302377,0.118383,-0.064941,-0.450204,0.361862

In [7]:
#If needed make the graphs of before and after data such as in the workflow, but for now just moving on to make the PCAs

In [ ]:
met_samples = (pd.Series(cleaned_data.columns, name="Sample").astype(str).str.strip())

met_samples = pd.DataFrame({"Sample": met_samples})


meta = pd.read_excel("43587_2024_572_MOESM4_ESM.xlsx", sheet_name="Fig 1a")
meta = meta[1:] 
meta.columns = meta.iloc[0]
meta = meta[meta['Metabolome'] == 1]
sample_to_info = meta.set_index('Macaca fascicularis Sample ID')[['Age', 'Gender','Region','Location']].to_dict(orient='index')

print(type(sample_to_info), len(sample_to_info))
print(list(sample_to_info.keys())[:5])  
meta_preview = pd.DataFrame.from_dict(sample_to_info, orient='index')
display(meta_preview.head(10))

<class 'dict'> 98
['2-22-A', '2-22-D', '2-22-R', '2-22-T', '2-25-A']

               Age  Gender    Region          Location
2-22-A  Middle age  Female  Proximal   Ascending colon
2-22-D  Middle age  Female    Distal  Descending colon
2-22-R  Middle age  Female    Distal            Rectum
2-22-T  Middle age  Female  Proximal  Transverse colon
2-25-A  Middle age  Female  Proximal   Ascending colon
2-25-D  Middle age  Female    Distal  Descending colon
2-25-R  Middle age  Female    Distal            Rectum
2-25-T  Middle age  Female    Distal  Transverse colon
3-28-A  Middle age  Female  Proximal   Ascending colon
3-28-D  Middle age  Female    Distal  Descending colon

In [ ]:
'''
import re

pat_norm = r'^(?P<Cohort>\d+)-(?P<Subject>\d+)-(?P<Segment>[ATDR])$'
pat_extra = r'^(?P<Female>[FM])-(?P<Segment>[ATDR])$'

segment_map = {'A': 'Ascending colon','T': 'Transverse colon','D': 'Descending colon','R': 'Rectum'}

rows = []

for col in map(str, cleaned_data.columns):
    m = re.match(pat_norm, col) or re.match(pat_extra, col)
    if m:
        sample_dict = m.groupdict()
        sample_dict['Sample'] = col
        sample_dict['Group'] = col
        rows.append(sample_dict)
    
sample_df = pd.DataFrame(rows)
if len(sample_df) == 0:
    print(f"Warning: No parsable sample names found in metabolomics column")

sample_df['Segment'] = sample_df['Segment'].map(segment_map)

# Remove duplicate samples (keeping track of which we've seen)
before = len(sample_df)
sample_df = sample_df.drop_duplicates(subset=['Sample'])
after = len(sample_df)
if before > after:
    print(f"Removed {before - after} duplicate samples")
'''


'''
this is a whole thing from the workflow about showing the counts for each type, but upon thinking I dont think its quite as relevant for this?
If needed can uncomment and start fixing
otherwise just moving onward to pca
# Count unique combinations by grouping variables
group_counts = (
    sample_df
    .groupby(['group', 'age', 'test'])
    .size()
    .reset_index(name = 'Count')
    .sort_values('Count', ascending=False)
)
    


# Show summary of all groups across sheets
print("\nAll experimental groups:")
all_groups_summary = group_counts.assign(Sheet='Extended Data Fig 1m')
display(all_groups_summary)
'''

'\nthis is a whole thing from the workflow about showing the counts for each type, but upon thinking I dont think its quite as relevant for this?\nIf needed can uncomment and start fixing\notherwise just moving onward to pca\n# Count unique combinations by grouping variables\ngroup_counts = (\n    sample_df\n    .groupby([\'group\', \'age\', \'test\'])\n    .size()\n    .reset_index(name = \'Count\')\n    .sort_values(\'Count\', ascending=False)\n)\n\n\n\n# Show summary of all groups across sheets\nprint("\nAll experimental groups:")\nall_groups_summary = group_counts.assign(Sheet=\'Extended Data Fig 1m\')\ndisplay(all_groups_summary)\n'

In [10]:
from umap.umap_ import UMAP
import seaborn as sns


meta_file = "43587_2024_572_MOESM4_ESM.xlsx"

meta_info = pd.read_excel(meta_file,sheet_name='Fig 1a')

meta = meta_info.copy()
meta = meta[1:]
meta.columns = meta.iloc[0]
meta = meta[meta['Metabolome'] == 1]

sample_to_info = meta.set_index('Macaca fascicularis Sample ID')[['Age', 'Gender','Region','Location']].to_dict(orient='index')  

combined_data = []
combined_metadata = []

df_t = preprocessed_scaled.T
combined_data.append(df_t)
combined_metadata.append(sample_to_info)

X_combined = pd.concat(combined_data, axis=0)
metadata_combined = pd.concat(combined_metadata, axis=0).reset_index(drop=True)

print(f"Combined data shape: {X_combined.shape}")
print(f"Metadata shape: {metadata_combined.shape}")

/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid